export default [
  { code: 'ERRPRJ1', message: 'No Email provided' },
  { code: 'ERRPRJ2', message: 'No match found' },
  { code: 'ERRPRJ3', message: "Email doesn't appear to be a valid address" },
  {
    code: 'ERRPRJ4',
    message: 'Invalid Email',
    description: 'No participant found with the email.',
  },
  { code: 'ERRPRJ5', message: 'Missing Project ID' },
  { code: 'ERRPRJ6', message: 'Invalid Project ID' },
  { code: 'ERRPRJ7', message: 'Malformed Project ID' },
  { code: 'ERRPRJ8', message: 'Malformed include_rater_details' },
  { code: 'ERRUSR1', message: 'Missing Email' },
  { code: 'ERRUSR2', message: "Email doesn't appear to be a valid address" },
  { code: 'ERRUSR3', message: 'Invalid Email' },
  { code: 'ERRASMT2', message: 'No match found' },
  { code: 'ERRASMT3', message: "Email doesn't appear to be a valid address" },
  { code: 'ERRRTR1', message: 'Missing Email' },
  { code: 'ERRRTR2', message: "Email doesn't appear to be a valid address" },
  { code: 'ERRRTR3', message: 'Invalid Email' },
  { code: 'ERRRTR4', message: 'Malformed Project ID(s)' },
  { code: 'ERRRTR5', message: 'Email not found in Project' },
];
